theme = "sloth"
baseurl = "https://www.somewhereonearth.xyz"
languageCode = "en-us"
title = "Somewhere on Earth"
pluralizelisttitles = false
[Params]
    Author = "Pierre Lespingal"
    disqusShortname = "Pierre"
